version: '3.4'

services:
  keycloakdb:
    container_name: keycloakdb
    image: mariadb:${MARIADB_VERSION:-10.6.8}
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASS:-r00t}
      MARIADB_DATABASE: ${MARIADB_DB:-keycloak}
      MARIADB_USER: ${MARIADB_USER:-keycloak}
      MARIADB_PASSWORD: ${MARIADB_PASS:-p@ssw0rd}
    # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  keycloak:
    container_name: keycloak
    #image: quay.io/keycloak/keycloak:19.0.1
    image: keycloak_image
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS:-admin}
      KC_HTTP_ENABLED: "true"
      #KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://keycloakdb:3306/${MARIADB_DB:-keycloak}?useSSL=false
      KC_DB_USERNAME: ${MARIADB_USER:-keycloak}
      KC_DB_PASSWORD: ${MARIADB_PASS:-p@ssw0rd}
      KC_LOG_LEVEL: debug
      KC_PROXY: edge
    depends_on:
      - keycloakdb

volumes:
  mariadb_data:
    driver: local