version: '3.4'

services:
  keycloakdb:
    ports:
      - 5647:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASS}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}

  keycloak:
    command: start --optimized
    ports:
      - 8443:8080
    environment:
      #KC_HOSTNAME: localhost
      KC_DB_USERNAME: ${MARIADB_USER}
      KC_DB_PASSWORD: ${MARIADB_PASS}