version: '3.4'

services:
  keycloakdb:
    ports:
      - 5647:3306

  keycloak:
    command: start-dev
    ports:
      - 8443:8080
    environment:
      KC_HTTP_ENABLED: "true"
      #KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
